name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: whoami
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Update instance git
        run: sudo git pull
      - name: Install composer
        run: sudo composer install
      - name: Migration
        run: sudo artisan migrate
      - name: Restart Apache
        run: sudo systemctl restart apache2